Repository MoAaDream/Giftogether, pull requests merged in 2024-07, with the labels that each got.

#89 feat: 악의적으로 환불하는 사람들에 대한 제한 기능 추가
  src/main/java/com/moadream/giftogether/funding/controller/FundingController.java
  src/main/java/com/moadream/giftogether/global/admin/controller/AdminController.java
  src/main/java/com/moadream/giftogether/global/admin/service/AdminService.java
  src/main/java/com/moadream/giftogether/member/MemberController.java
  src/main/java/com/moadream/giftogether/member/MemberRepository.java
  src/main/java/com/moadream/giftogether/member/exception/MemberExceptionCode.java
  src/main/java/com/moadream/giftogether/member/model/Member.java
  src/main/java/com/moadream/giftogether/member/service/MemberService.java
  src/main/java/com/moadream/giftogether/product/controller/ProductController.java
  src/main/java/com/moadream/giftogether/wishlist/controller/WishListController.java
  src/main/resources/templates/admin/blacklist.html
Labels: feat

#100 Feat: Feat : 펀딩 종료시 기능 추가 및 수정
  src/main/java/com/moadream/giftogether/Controller.java
  src/main/java/com/moadream/giftogether/bank/controller/BankController.java
  src/main/java/com/moadream/giftogether/bank/model/Bank.java
  src/main/java/com/moadream/giftogether/bank/model/BankForm.java
  src/main/java/com/moadream/giftogether/bank/repository/BankRepository.java
  src/main/java/com/moadream/giftogether/bank/service/BankService.java
  src/main/java/com/moadream/giftogether/funding/controller/FundingController.java
  src/main/java/com/moadream/giftogether/funding/model/RequestPayDto.java
  src/main/java/com/moadream/giftogether/funding/service/FundingService.java
  src/main/java/com/moadream/giftogether/funding/service/PaymentService.java
  src/main/java/com/moadream/giftogether/global/admin/service/AdminService.java
  src/main/java/com/moadream/giftogether/member/model/Member.java
  src/main/java/com/moadream/giftogether/member/service/MemberService.java
  src/main/java/com/moadream/giftogether/product/Service/ProductService.java
  src/main/java/com/moadream/giftogether/product/controller/ProductController.java
  src/main/resources/templates/example.html
  src/main/resources/templates/footer.html
  src/main/resources/templates/funding/order.html
  src/main/resources/templates/funding/payment.html
  src/main/resources/templates/header.html
  src/main/resources/templates/layout.html
  src/main/resources/templates/navbar.html
  src/main/resources/templates/products/product_detail.html
Labels: feat

#98 feat: wishlist, product 폼 디자인 수정
  src/main/resources/templates/home.html
  src/main/resources/templates/products/product_form.html
  src/main/resources/templates/products/product_modify.html
  src/main/resources/templates/products/product_mylist.html
  src/main/resources/templates/wishlists/wishlist_form.html
  src/main/resources/templates/wishlists/wishlist_modifyform.html
  src/main/resources/templates/wishlists/wishlists.html
Labels: feat

#102 feat: 모금 완료시 이메일 전송 기능 추가
  build.gradle
  src/main/java/com/moadream/giftogether/funding/service/PaymentService.java
  src/main/java/com/moadream/giftogether/global/email/EmailService.java
  src/main/java/com/moadream/giftogether/global/email/MailConfig.java
  src/main/resources/application-main.properties
Labels: feat

#104 fix: date formatting 에러 수정
  src/main/resources/templates/admin/blacklist.html
Labels: bug

#107 feat: 펀딩 큐
  src/main/java/com/moadream/giftogether/PortoneConfig.java
  src/main/java/com/moadream/giftogether/funding/controller/FundingController.java
  src/main/java/com/moadream/giftogether/funding/model/FundingRequest.java
  src/main/java/com/moadream/giftogether/funding/service/FundingQueueManager.java
  src/main/java/com/moadream/giftogether/funding/service/FundingService.java
  src/main/java/com/moadream/giftogether/funding/service/PaymentService.java
  src/main/java/com/moadream/giftogether/global/email/EmailService.java
  src/main/java/com/moadream/giftogether/global/email/MailConfig.java
  src/main/java/com/moadream/giftogether/product/Repository/ProductRepository.java
  src/main/java/com/moadream/giftogether/product/Service/ProductService.java
  src/main/java/com/moadream/giftogether/product/controller/ProductController.java
  src/main/java/com/moadream/giftogether/wishlist/service/WishListService.java
  src/main/resources/application-test.properties
  src/main/resources/application.properties
  src/main/resources/static/css/ttt.css
  src/main/resources/templates/funding/order.html
  src/main/resources/templates/funding/payment.html
  src/main/resources/templates/funding/paymentt.html
  src/main/resources/templates/products/product_detail.html
Labels: feat

#109 feat: 결제 디자인
  src/main/java/com/moadream/giftogether/PortoneConfig.java
  src/main/java/com/moadream/giftogether/funding/controller/FundingController.java
  src/main/java/com/moadream/giftogether/funding/model/FundingDetailsDTO.java
  src/main/java/com/moadream/giftogether/funding/model/FundingRequest.java
  src/main/java/com/moadream/giftogether/funding/repository/FundingRepository.java
  src/main/java/com/moadream/giftogether/funding/repository/PaymentRepository.java
  src/main/java/com/moadream/giftogether/funding/service/FundingQueueManager.java
  src/main/java/com/moadream/giftogether/funding/service/FundingService.java
  src/main/java/com/moadream/giftogether/member/MemberController.java
  src/main/java/com/moadream/giftogether/product/Repository/ProductRepository.java
  src/main/java/com/moadream/giftogether/product/Service/ProductService.java
  src/main/java/com/moadream/giftogether/product/controller/ProductController.java
  src/main/java/com/moadream/giftogether/wishlist/controller/WishListController.java
  src/main/java/com/moadream/giftogether/wishlist/model/WishList.java
  src/main/java/com/moadream/giftogether/wishlist/model/WishListForm.java
  src/main/java/com/moadream/giftogether/wishlist/model/WishlistDto.java
  src/main/java/com/moadream/giftogether/wishlist/repository/WishListRepository.java
  src/main/java/com/moadream/giftogether/wishlist/service/WishListService.java
  src/main/resources/static/css/ttt.css
  src/main/resources/templates/funding/order.html
  src/main/resources/templates/funding/payment.html
  src/main/resources/templates/home.html
  src/main/resources/templates/member/pay_statics.html
  src/main/resources/templates/products/product_detail.html
Labels: feat

#120 Style : 펀딩 리스트 디자인 추가
  src/main/java/com/moadream/giftogether/funding/controller/FundingController.java
  src/main/java/com/moadream/giftogether/funding/controller/PaymentController.java
  src/main/java/com/moadream/giftogether/funding/model/FundingDetailsDTO.java
  src/main/java/com/moadream/giftogether/funding/service/FundingService.java
  src/main/java/com/moadream/giftogether/member/MemberController.java
  src/main/java/com/moadream/giftogether/message/controller/MessageController.java
  src/main/java/com/moadream/giftogether/message/repository/MessageRepository.java
  src/main/java/com/moadream/giftogether/message/service/MessageService.java
  src/main/java/com/moadream/giftogether/product/Service/ProductService.java
  src/main/java/com/moadream/giftogether/product/controller/ProductController.java
  src/main/java/com/moadream/giftogether/wishlist/model/WishlistDto.java
  src/main/resources/templates/funding/detail.html
  src/main/resources/templates/funding/order.html
  src/main/resources/templates/funding/payment.html
  src/main/resources/templates/member/pay_statics.html
  src/main/resources/templates/products/product_detail.html
Labels: feat

#119 feat: 위시리스트 생성시 제한 추가
  src/main/java/com/moadream/giftogether/message/model/Message.java
  src/main/java/com/moadream/giftogether/wishlist/controller/WishListController.java
  src/main/java/com/moadream/giftogether/wishlist/exception/WishlistExceptionCode.java
  src/main/java/com/moadream/giftogether/wishlist/service/WishListService.java
  src/main/resources/templates/main.html
Labels: feat

#123 Style : 디자인 조금 수정 , 테스트 실패
  src/main/java/com/moadream/giftogether/funding/controller/FundingController.java
  src/main/java/com/moadream/giftogether/funding/model/FundingRequest.java
  src/main/java/com/moadream/giftogether/funding/service/FundingService.java
  src/main/resources/templates/admin/blacklist.html
  src/main/resources/templates/admin/statics.html
  src/main/resources/templates/funding/detail.html
  src/main/resources/templates/funding/order.html
  src/main/resources/templates/products/product_detail.html
Labels: bug, feat

#129 feat: 계좌 환불 위치 이동
  src/main/java/com/moadream/giftogether/bank/controller/BankController.java
  src/main/java/com/moadream/giftogether/funding/controller/FundingController.java
  src/main/resources/templates/funding/myaccount.html
  src/main/resources/templates/products/product_mydetail.html
Labels: feat

#138 style : 리뷰하고 머지 바로해주세요
  src/main/java/com/moadream/giftogether/global/admin/controller/AdminController.java
  src/main/java/com/moadream/giftogether/member/MemberController.java
  src/main/resources/templates/admin/blacklist.html
  src/main/resources/templates/admin/index.html
  src/main/resources/templates/admin/statics.html
  src/main/resources/templates/funding/myaccount.html
  src/main/resources/templates/funding/order.html
  src/main/resources/templates/funding/payment.html
  src/main/resources/templates/member/mypage.html
  src/main/resources/templates/products/product_mydetail.html
Labels: feat

#140 Fix : jquery 수정
  src/main/java/com/moadream/giftogether/funding/controller/FundingController.java
  src/main/resources/application.properties
  src/main/resources/templates/funding/payment.html
  src/main/resources/templates/products/product_mydetail.html
Labels: bug

#141 docs: readme 작성
  .gitattributes
  README.md
Labels: documentation

#142 fix: 불필요한 html 코드 삭제
  src/main/resources/templates/member/friendList.html
Labels: bug
